services:
  rbp-auth:
    image: mwinteringham/restfulbookerplatform_auth:2.0.05d68b8
    ports:
      - "3004:3004"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006

  rbp-booking:
    image: mwinteringham/restfulbookerplatform_booking:2.0.05d68b8
    ports:
      - "3000:3000"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006
    depends_on:
      rbp-auth:
        condition: service_started

  rbp-room:
    image: mwinteringham/restfulbookerplatform_room:2.0.05d68b8
    ports:
      - "3001:3001"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006
    depends_on:
      rbp-auth:
        condition: service_started

  rbp-branding:
    image: mwinteringham/restfulbookerplatform_branding:2.0.05d68b8
    ports:
      - "3002:3002"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006
    depends_on:
      rbp-auth:
        condition: service_started

  rbp-report:
    image: mwinteringham/restfulbookerplatform_report:2.0.05d68b8
    ports:
      - "3005:3005"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006
    depends_on:
      rbp-auth:
        condition: service_started

  rbp-message:
    image: mwinteringham/restfulbookerplatform_message:2.0.05d68b8
    ports:
      - "3006:3006"
    restart: always
    platform: linux/amd64
    environment:
      - API_HOST=rbp-booking:3000
      - AUTH_HOST=rbp-auth:3004
      - ROOM_HOST=rbp-room:3001
      - REPORT_HOST=rbp-report:3005
      - MESSAGE_HOST=rbp-message:3006
    depends_on:
      rbp-auth:
        condition: service_started

  rbp-assets:
    image: mwinteringham/restfulbookerplatform_assets:2.0.f5e8d6c
    ports:
      - "80:80"
    restart: always
    platform: linux/amd64
    environment:
      - REACT_APP_API_HOST=http://rbp-booking:3000
      - REACT_APP_AUTH_HOST=http://rbp-auth:3004
      - REACT_APP_REPORT_HOST=http://rbp-report:3005
      - REACT_APP_MESSAGE_HOST=http://rbp-message:3006
      - REACT_APP_ROOM_HOST=http://rbp-room:3001
      - NODE_ENV=development
    depends_on:
      rbp-booking:
        condition: service_started
      rbp-auth:
        condition: service_started
      rbp-room:
        condition: service_started
      rbp-branding:
        condition: service_started
      rbp-report:
        condition: service_started
      rbp-message:
        condition: service_started